[package]
name = "gengine_clipboard"
version = "0.0.0"
edition = "2024"

[lib]
crate-type = ["lib"]

[dependencies]
image = "0.25.6"
reqwest = { version = "0.12.20", features = [
	"blocking",
	"rustls-tls",
], optional = true }

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.61.1", features = [
	"Win32_Foundation",
	"Win32_System_DataExchange",
	"Win32_UI_WindowsAndMessaging",
	"Win32_UI_Shell",
	"Win32_System_Memory",
	"Win32_System_DataExchange",
	"Win32_Graphics_Gdi",
	"Win32_System_LibraryLoader",
] }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3"

[features]
default = []
follow_links = ["dep:reqwest"]
follow_html_img = ["dep:reqwest"]
